// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: simple_rpc.proto

package simple_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SimpleRpc_Ping_FullMethodName = "/simple_rpc.simple_rpc/Ping"
)

// SimpleRpcClient is the client API for SimpleRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleRpcClient interface {
	// Ping 测试
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type simpleRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleRpcClient(cc grpc.ClientConnInterface) SimpleRpcClient {
	return &simpleRpcClient{cc}
}

func (c *simpleRpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, SimpleRpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleRpcServer is the server API for SimpleRpc service.
// All implementations must embed UnimplementedSimpleRpcServer
// for forward compatibility
type SimpleRpcServer interface {
	// Ping 测试
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSimpleRpcServer()
}

// UnimplementedSimpleRpcServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleRpcServer struct {
}

func (UnimplementedSimpleRpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSimpleRpcServer) mustEmbedUnimplementedSimpleRpcServer() {}

// UnsafeSimpleRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleRpcServer will
// result in compilation errors.
type UnsafeSimpleRpcServer interface {
	mustEmbedUnimplementedSimpleRpcServer()
}

func RegisterSimpleRpcServer(s grpc.ServiceRegistrar, srv SimpleRpcServer) {
	s.RegisterService(&SimpleRpc_ServiceDesc, srv)
}

func _SimpleRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleRpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleRpc_ServiceDesc is the grpc.ServiceDesc for SimpleRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simple_rpc.simple_rpc",
	HandlerType: (*SimpleRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SimpleRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simple_rpc.proto",
}
